# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Mehrdad <br> Hosseinzadeh
tagline:          'Home'
description:      'PhD student of <a href="http://cs.umanitoba.ca">Computer Science</a> at <a href="http://umanitoba.ca">University of Manitoba</a>, Winnipeg, MB. <br> <a href="https://twitter.com/hzmehrdad"  class="theme-base-0b" style="color: #38A1F3; padding-right: 1em"><i class="fab fa-twitter"></i></a><a href="mailto:mehrdad@cs.umanitoba.ca" style="color: #239B56; padding-right: 1em"><i class="fas fa-at"></i></a><a href="https://www.linkedin.com/in/mehrdadhosseinzadeh/" style="color: #0077B5"><i class="fab fa-linkedin-in"></i></a>'
#'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2018.11.27

github:
  repo:           https://github.com/poole/hyde
